version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: react-scripts
    versions:
    - 4.0.2
  - dependency-name: node-notifier
    versions:
    - 8.0.1
